# Generated by Django 4.2.4 on 2023-08-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otpio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userphoneotp',
            name='status',
        ),
        migrations.AddField(
            model_name='userphoneotp',
            name='is_consumed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userphoneotp',
            name='otp',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
