# Generated by Django 4.2.4 on 2023-10-06 10:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accountio", "0011_alter_transactionorganizationuser_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("threadio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thread",
            name="participants",
        ),
        migrations.RemoveField(
            model_name="thread",
            name="reply_count",
        ),
        migrations.RemoveField(
            model_name="thread",
            name="title",
        ),
        migrations.AddField(
            model_name="thread",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="thread",
            name="is_send_by_customer",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="inbox",
            unique_together={("user", "organization")},
        ),
        migrations.AlterIndexTogether(
            name="inbox",
            index_together={("user", "organization")},
        ),
        migrations.RemoveField(
            model_name="inbox",
            name="kind",
        ),
    ]
