# Generated by Django 4.2.2 on 2023-07-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountio', '0002_organizationuser_organization_organizationuser_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationuser',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('STAFF', 'Staff'), ('CUSTOMER', 'Customer'), ('DELIVERER', 'Deliverer')], max_length=20),
        ),
    ]
