# Generated by Django 4.2.4 on 2023-08-22 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderio', '0005_returnorderproduct_is_return_by_merchant'),
        ('accountio', '0004_organization_contact_number_organization_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionorganizationuser',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orderio.order'),
        ),
    ]
