# Generated by Django 4.2.4 on 2023-09-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accountio", "0006_alter_organization_contact_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="delivery_charge",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
