# Generated by Django 4.2.4 on 2023-09-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accountio", "0008_historicaltransactionorganizationuser_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalorganization",
            name="delivery_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="organization",
            name="delivery_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
