# Generated by Django 4.2.4 on 2023-09-27 06:18

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("accountio", "0009_alter_historicalorganization_delivery_charge_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorganization",
            name="logo",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalorganization",
            name="logo_height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalorganization",
            name="logo_ppoi",
            field=versatileimagefield.fields.PPOIField(
                default="0.5x0.5", editable=False, max_length=20
            ),
        ),
        migrations.AddField(
            model_name="historicalorganization",
            name="logo_width",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="logo",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True,
                height_field="logo_height",
                null=True,
                upload_to="",
                width_field="logo_width",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="logo_height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="logo_ppoi",
            field=versatileimagefield.fields.PPOIField(
                default="0.5x0.5", editable=False, max_length=20
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="logo_width",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
