# Generated by Django 4.2.4 on 2023-09-27 11:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accountio", "0010_historicalorganization_logo_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transactionorganizationuser",
            options={},
        ),
    ]
