# Generated by Django 4.2.4 on 2023-09-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notificationio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationuserpreference",
            name="enable_cart_notification",
            field=models.CharField(
                choices=[
                    ("ON", "On"),
                    ("OFF", "Off"),
                    ("OFF BY ADMIN", "Off by admin"),
                ],
                default="ON",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="notificationuserpreference",
            name="enable_cart_product_notification",
            field=models.CharField(
                choices=[
                    ("ON", "On"),
                    ("OFF", "Off"),
                    ("OFF BY ADMIN", "Off by admin"),
                ],
                default="ON",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="model_type",
            field=models.CharField(
                choices=[
                    ("USER", "User"),
                    ("ORGANIZATION", "Organization"),
                    ("ORGANIZATION_USER", "Organization User"),
                    ("PRODUCT", "Product"),
                    ("ORDER", "Order"),
                    ("ORDER_DELIVERY", "Order Delivery"),
                    ("CART", "Cart"),
                    ("CART_PRODUCT", "Cart Product"),
                ],
                max_length=30,
            ),
        ),
    ]
