# Generated by Django 4.2.5 on 2023-10-03 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notificationio', '0003_alter_notificationuserreceiver_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodelconnector',
            name='notification',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notificationio.notification'),
        ),
    ]
