# Generated by Django 4.2 on 2023-06-02 17:06

import dirtyfields.dirtyfields
from django.db import migrations, models
import django.db.models.deletion
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', versatileimagefield.fields.VersatileImageField(height_field='height', upload_to='', width_field='width')),
                ('width', models.PositiveIntegerField(blank=True)),
                ('height', models.PositiveIntegerField(blank=True)),
                ('ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
                ('caption', models.CharField(blank=True, max_length=100, null=True)),
                ('copyright', models.CharField(blank=True, max_length=100, null=True)),
                ('priority', models.BigIntegerField(default=0)),
                ('kind', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], db_index=True, max_length=20)),
            ],
            options={
                'ordering': ('-created_at',),
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MediaImageConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('UNDEFINED', 'Undefined'), ('BASE_PRODUCT', 'Base Product'), ('PRODUCT', 'Product')], db_index=True, default='UNDEFINED', max_length=20)),
                ('base_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogio.baseproduct')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mediaroomio.mediaimage')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogio.product')),
            ],
            options={
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
