# Generated by Django 4.2.2 on 2023-07-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressio', '0002_address_user_alter_upazila_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_storefront',
            field=models.BooleanField(default=False, help_text='Checking if this address is a storefront or not.'),
        ),
    ]
