# Generated by Django 4.2.1 on 2023-06-06 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogio', '0002_baseproduct_active_ingredients_baseproduct_brand_and_more'),
        ('orderio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnorderproduct',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogio.product'),
            preserve_default=False,
        ),
    ]
