# Generated by Django 4.2.4 on 2023-08-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orderio", "0003_order_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdelivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("ORDER_PLACED", "Order Placed"),
                    ("ACCEPTED", "Accepted"),
                    ("PROCESSING", "Processing"),
                    ("PACKAGING", "Packaging"),
                    ("PARTIAL_DELIVERY", "Partial Delivery"),
                    ("WAITING_FOR_DELIVERER", "Waiting For Deliverer"),
                    ("ON_THE_WAY", "On The Way"),
                    ("PARTIAL_RETURNED", "Partial Returned"),
                    ("RETURNED", "Returned"),
                    ("CANCELED", "Canceled"),
                    ("COMPLETED", "Completed"),
                ],
                default="ORDER_PLACED",
                max_length=50,
            ),
        ),
    ]
