# Generated by Django 4.2.4 on 2023-08-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderio', '0004_alter_orderdelivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnorderproduct',
            name='is_return_by_merchant',
            field=models.BooleanField(default=False),
        ),
    ]
