# Generated by Django 4.2.4 on 2023-09-18 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogio', '0008_historicalproduct_historicalbaseproduct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accountio', '0008_historicaltransactionorganizationuser_and_more'),
        ('paymentio', '0001_initial'),
        ('orderio', '0006_order_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalReturnOrderProduct',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('returned_quantity', models.PositiveIntegerField(default=0)),
                ('is_return_by_merchant', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=800)),
                ('description', models.TextField(blank=True)),
                ('is_damage', models.BooleanField(help_text='If true, this will save to product damage_stock, otherwise it will save to product stock')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orderio.order')),
                ('order_product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orderio.orderproduct')),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accountio.organization')),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogio.product')),
            ],
            options={
                'verbose_name': 'historical return order product',
                'verbose_name_plural': 'historical return order products',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOrderDelivery',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('status', models.CharField(choices=[('ORDER_PLACED', 'Order Placed'), ('ACCEPTED', 'Accepted'), ('PROCESSING', 'Processing'), ('PACKAGING', 'Packaging'), ('PARTIAL_DELIVERY', 'Partial Delivery'), ('WAITING_FOR_DELIVERER', 'Waiting For Deliverer'), ('ON_THE_WAY', 'On The Way'), ('PARTIAL_RETURNED', 'Partial Returned'), ('RETURNED', 'Returned'), ('CANCELED', 'Canceled'), ('COMPLETED', 'Completed')], default='ORDER_PLACED', max_length=50)),
                ('stage', models.CharField(choices=[('PENDING', 'Pending'), ('CURRENT', 'Current'), ('COMPLETED', 'Completed')], max_length=15)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orderio.order')),
            ],
            options={
                'verbose_name': 'historical order delivery',
                'verbose_name_plural': 'historical order deliverys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('serial_number', models.PositiveIntegerField(blank=True, db_index=True, editable=False)),
                ('order_price', models.DecimalField(decimal_places=2, default=0, help_text='This is a price which is initially created by a customer', max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, help_text='This is include the discount_offset percent offer', max_digits=10)),
                ('payable_amount', models.DecimalField(decimal_places=2, default=0, help_text='This is the amount which will be paid by a customer', max_digits=10)),
                ('discount_offset', models.DecimalField(decimal_places=2, default=0, help_text='This is the customer special offer which is given by a organization.', max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='This is discount will appy on order total price, only accept percentage.', max_digits=10)),
                ('address', models.JSONField()),
                ('completed', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('receiver_name', models.CharField(blank=True, max_length=150)),
                ('receiver_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accountio.organization')),
                ('payment_method', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='paymentio.paymentmethod')),
            ],
            options={
                'verbose_name': 'historical order',
                'verbose_name_plural': 'historical orders',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
