# Generated by Django 4.2 on 2023-06-02 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addressio', '0002_address_user_alter_upazila_unique_together'),
        ('accountio', '0002_organizationuser_organization_organizationuser_user_and_more'),
        ('catalogio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproduct',
            name='active_ingredients',
            field=models.ManyToManyField(blank=True, to='catalogio.ingredient'),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogio.brand'),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogio.category'),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='dosage_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogio.dosageform'),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogio.manufacturer'),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='medicine_physical_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogio.medicinephysicalstate'),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='merchant_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogio.product'),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='route_of_administration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogio.routeofadministration'),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='superadmin',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('is_superuser', True), ('is_staff', True), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='catalogio.category'),
        ),
        migrations.AddField(
            model_name='deliverycharge',
            name='admin',
            field=models.ForeignKey(blank=True, default=1, limit_choices_to=models.Q(('is_superuser', True), ('is_staff', True), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverycharge',
            name='district',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='addressio.district'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accountio.organization'),
            preserve_default=False,
        ),
    ]
