# Generated by Django 4.2.2 on 2023-06-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogio', '0002_baseproduct_active_ingredients_baseproduct_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='box_type',
            field=models.CharField(choices=[('WITH BOX', 'With box'), ('WITHOUT BOX', 'Without box')], default='WITH BOX', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('HIDDEN', 'Hidden'), ('REMOVED', 'Removed')], db_index=True, default='PENDING', max_length=50),
        ),
    ]
