# Generated by Django 4.2.2 on 2023-07-12 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountio', '0002_organizationuser_organization_organizationuser_user_and_more'),
        ('catalogio', '0003_product_box_type_alter_category_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('organization', 'base_product', 'box_type')},
        ),
    ]
