# Generated by Django 4.2.2 on 2023-07-28 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogio', '0004_alter_product_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproduct',
            name='merchant_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogio.product'),
        ),
    ]
