# Generated by Django 4.2.2 on 2023-08-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogio', '0005_alter_baseproduct_merchant_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproduct',
            name='unit',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
