# Generated by Django 4.2.4 on 2023-08-30 07:31

import autoslug.fields
import catalogio.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogio', '0006_alter_baseproduct_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproduct',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from=catalogio.utils.get_base_product_slug, unique=True),
        ),
    ]
