# Generated by Django 4.2.4 on 2023-09-13 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accountio", "0006_alter_organization_contact_number_and_more"), 
        ("addressio", "0003_address_is_storefront"),
        ("catalogio", "0007_baseproduct_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverycharge",
            name="organization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="accountio.organization",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="deliverycharge",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="addressio.district"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="deliverycharge",
            unique_together={("district", "organization")},
        ),
    ]
