# Generated by Django 4.2.4 on 2023-09-19 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogio', '0008_historicalproduct_historicalbaseproduct'),
        ('catalogio', '0009_remove_deliverycharge_admin'),
    ]

    operations = [
    ]
